### ISSUE TITLE
clarify Series.combine_first

### ISSUE THREAD

**Issue by MarcoGorelli** [MarcoGorelli/pyladies-sprint-April-2021#1]
Docs are unclear:

https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.combine_first.html?highlight=combine_first#pandas.DataFrame.combine_first

https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.Series.combine_first.html?highlight=combine_first#pandas.Series.combine_first

DataFrame is alright, but Series is unclear. Can the docs be shared?

**Comment by HeidiNeuhaeuser** [comment]
I'll look into this
