### ISSUE TITLE
add example to swaplevel

### ISSUE THREAD

**Issue by MarcoGorelli** [MarcoGorelli/pyladies-sprint-April-2021#13]
https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.swaplevel.html?highlight=swaplevel#pandas.DataFrame.swaplevel

No examples! Can we add one?

**Comment by thordisstella** [comment]
Posting for visibility: I'm looking at this one

**Comment by thordisstella** [comment]
I have created a PR here:https://github.com/pandas-dev/pandas/pull/40269. Was there anything else that I need to do? For example assign it to someone in particular? Or do I just leave it and wait?

**Comment by MarcoGorelli** [comment]
Thanks @thordisstella ! That's all, I'll review when I get a chance
